In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
ds = tf.constant(x_train, shape=(60000, 1, 28*28), dtype=tf.float64)

In [4]:
ds[0].shape

TensorShape([1, 784])

In [5]:
from Network import Network

In [6]:
nn = Network([28*28, 128, 10])

In [7]:
nn.build()

In [8]:
ds[0:2].shape

TensorShape([2, 1, 784])

In [9]:
tf.reshape(ds[0:2], shape=[2,784,1])

<tf.Tensor: shape=(2, 784, 1), dtype=float64, numpy=
array([[[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]])>

In [10]:
nn.forward(ds[0:2])

<tf.Tensor: shape=(2, 1, 10), dtype=float64, numpy=
array([[[0.6797282 , 0.500004  , 0.56150327, 0.73105729, 0.50085611,
         0.50109518, 0.73065371, 0.70022924, 0.53617261, 0.68269239]],

       [[0.62424589, 0.52538251, 0.59459195, 0.73105855, 0.50022832,
         0.69786055, 0.72021955, 0.724803  , 0.51203102, 0.64754339]]])>